# Generated by Django 4.0.5 on 2022-07-05 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_profesores_rename_curso_cursos_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cursos',
            old_name='camada',
            new_name='comision',
        ),
    ]
